# Use the official Node.js 16 image.
# https://hub.docker.com/_/node
FROM node:16

# Create and change to the app directory.
WORKDIR /app

# Copy package.json and package-lock.json to the container.
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Set the command to run your app using CMD which defines your runtime.
# Here we will use node to run the application.
CMD ["node", "server.js"]
