name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Dependabot
        uses: github/codeql-action/init-dependabot@v1

