name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build and deploy to Netlify
        run: netlify deploy --prod --auth ${{ secrets.ASSIGNMENT_NETLIFY_AUTH_TOKEN }}
